version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/euDigital
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build: ./frontEnd
    container_name: frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

volumes:
  mongo_data: